### ISSUE TITLE
Reparametrized Beta model: how to deal with unstability

### ISSUE THREAD

**Issue by DominiqueMakowski** [DominiqueMakowski/SubjectiveScalesModels.jl#2]
@kiante-fernandez @itsdfish could I pick your brain on the following:

I have defined `BetaPhi2` as literally a (reparametrized) beta distribution:

https://github.com/DominiqueMakowski/SubjectiveScalesModels.jl/blob/ad0f843ad9ee4515734974a3a44b72a63ffb725b/src/BetaPhi2.jl#L34-L36

However, when using it in Turing models, despite using a logit-link on mu, it very often fails with the following issue: 

https://dominiquemakowski.github.io/SubjectiveScalesModels.jl/dev/BetaPhi2/#Bayesian-Model-with-Turing

Suggesting that the evaluated mu is == 0 or 1 (which shouldn't be possible), so I suspect that it might be caused with values too close to zero. 

It seems to get fixed If I add:

```julia
if (μ_raw <= eps()) | (μ_raw >= 1 - eps())
       Turing.@addlogprob! -Inf
       return nothing
end
```

But it's not very elegant (and looks like a hack). Is there a way to deal with this more upstream? For instance, could we make the `logpdf()` of `BetaPhi2` more robust? 
I'm very much outside of my comfort zone here so any thoughts are welcome!

**Comment by itsdfish** [comment]
Looks like an interesting package. At a quick glace, your solution seems reasonable since the parameters of a beta distribution must be greater than 0. I'll take a closer look when I have more time later today.

**Comment by itsdfish** [comment]
I have a few moments for a few quick comments. I think your solution is reasonable. Another solution is to insert  similar logic directly into your `logpdf` function. I recommend a few changes in either case. For example, always return the type corresponding to the constructor. So [here](https://github.com/DominiqueMakowski/SubjectiveScalesModels.jl/blob/0c268cfc8fab923e02f42135c1e431ce37ade630/src/BetaPhi2.jl#L35), change to BetaPhi2.  `logpdf` should look similar to:

```julia 
function logpdf(dist::BetaPhi2, x::Real)
    (;μ ,  ϕ) = dist 
     return logpdf(Beta(μ * 2 * ϕ,  2 * ϕ * (1 - μ)) , x)
 end
```

And if you want to handle the case where beta parameters are zero, you can  modify the definition above.

```julia 
function logpdf(dist::BetaPhi2, x::Real)
    (;μ ,  ϕ) = dist 
     # your logic here to return -Inf
     return logpdf(Beta(μ * 2 * ϕ,  2 * ϕ * (1 - μ)) , x)
 end
```

It might be good to note that in your doc string, since it handles parameter values of 0 differently than in Distributions.jl

If there is a possibility that people might want to modify/extend the functionality of this type, you might consider making an abstract type and using `logpdf(dist::AbstractBetaPhi2, x::Real)` in your definition instead.

**Comment by DominiqueMakowski** [comment]
Amazing thanks so much @itsdfish 

It seems like adding:

https://github.com/DominiqueMakowski/SubjectiveScalesModels.jl/blob/f91e541a275e7d8079fb6a7992171188fb54f80e/src/BetaPhi2.jl#L78-L83

Fixed the issue! 

Don't hesitate if you have any other suggestions :)

**Comment by itsdfish** [comment]
No problem! 

After a cursory inspection, I think everything looks good. Nothing seemed off.  There are a few minor things you might consider.  Using bots for automatic formatting and benchmarking can be helpful. A working example can be found at SequentialSamplingModels.jl.
